{
 "title": "GameDb Stats",
 "tags": [
  "gamedb",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "protocol", "label": "protocol", "query": "label_values(protocol)" },
   { "name": "quantile", "label": "quantile", "query": "label_values(quantile)" }
  ]
 },
 "panels": [
  {
   "title": "Request Duration Summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gamedb_request_duration_seconds{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}}, {{protocol}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Request Duration Sum Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(gamedb_request_duration_seconds_sum{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\"}[5m])",
     "legendFormat": "{{protocol}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "Request Duration Count Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gamedb_request_duration_seconds_count{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\"}[5m])",
     "legendFormat": "{{protocol}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "Response Size Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gamedb_response_size_bytes{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}}, {{protocol}}, {{quantile}}"
    }
   ]
  },
  {
   "title": "Response Size Sum Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(gamedb_response_size_bytes_sum{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\"}[5m])",
     "legendFormat": "{{protocol}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "Response Size Count Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gamedb_response_size_bytes_count{instance=~\"$instance\",job=\"gamedb\",protocol=~\"$protocol\"}[5m])",
     "legendFormat": "{{protocol}}[{{instance}}]"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gamedb_request_errors_total{instance=~\"$instance\",job=\"gamedb\"}[5m])"
    }
   ]
  }
 ]
}