{
 "title": "HTTP API Stats",
 "tags": [
  "jersey",
  "http",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" },
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "e_class_name", "label": "e_class_name", "query": "label_values(class_name)" },
   { "name": "response_code", "label": "response_code", "query": "label_values(status)" },
   { "name": "uri", "label": "uri", "query": "label_values(uri)" },
   { "name": "interval", "label": "interval", "query": "label_values(interval)" }
  ]
 },
 "panels": [
  {
   "title": "Request Total Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jersey_requests_total{instance=~\"$instance\",job=~\"$job\",uri=~\"$uri\"}[5m])",
     "legendFormat": "instance=\"{{instance}}\",job=\"{{job}}\",uri=\"{{uri}}\""
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jersey_request_duration_avg_seconds{instance=~\"$instance\",job=~\"$job\",uri=~\"$uri\",interval=~\"$interval\"}",
     "legendFormat": "avg[{{job}}, {{uri}}, {{interval}}]"
    },
    {
     "expr": "jersey_request_duration_min_seconds{instance=~\"$instance\",job=~\"$job\",uri=~\"$uri\",interval=~\"$interval\"}",
     "legendFormat": "min[{{job}}, {{uri}}, {{interval}}]"
    },
    {
     "expr": "jersey_request_duration_max_seconds{instance=~\"$instance\",job=~\"$job\",uri=~\"$uri\",interval=~\"$interval\"}",
     "legendFormat": "max[{{job}}, {{uri}}, {{interval}}]"
    }
   ]
  },
  {
   "title": "Response Code Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(jersey_responses_total{instance=~\"$instance\",job=~\"$job\",status=~\"$response_code\"}) / sum(jersey_responses_total{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "response_code_ratio"
    }
   ]
  },
  {
   "title": "Exception Mappings Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jersey_exception_mappings_successful_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "successful[{{job}}]"
    },
    {
     "expr": "rate(jersey_exception_mappings_unsuccessful_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "unsuccessful[{{job}}]"
    },
    {
     "expr": "rate(jersey_exception_mappings_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "total[{{job}}]"
    }
   ]
  },
  {
   "title": "Exception Execution With Classname Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jersey_exception_mapper_execution_total{instance=~\"$instance\",class_name=~\"$e_class_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{class_name}}[{{job}}]"
    }
   ]
  }
 ]
}