{
 "title": "JVM Stats",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "prometheus",
  "jvm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}, {{job}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}, {{job}}"
    }
   ]
  },
  {
   "title": "Max fds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}, {{job}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{area}} memory [{{instance}}, {{job}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "current [{{instance}}, {{job}}]"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "daemon [{{instance}}, {{job}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "loaded [{{instance}}, {{job}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}, {{job}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{gc}} [{{instance}}, {{job}}]"
    }
   ]
  }
 ]
}