{
 "title": "Vert.x HTTP Stats",
 "tags": [
  "prometheus",
  "vert.x",
  "http"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "job", "label": "job", "query": "label_values(job)" },
   { "name": "path", "label": "path", "query": "label_values(path)" },
   { "name": "response_code", "label": "response_code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  {
   "title": "Http traffic data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(vertx_httpserver_bytes{instance=~\"$instance\",job=~\"$job\",type=\"read\"}[1m])",
     "legendFormat": "Request bytes"
    },
    {
     "expr": "rate(vertx_httpserver_bytes{instance=~\"$instance\",job=~\"$job\",type=\"written\"}[1m])",
     "legendFormat": "Respone bytes"
    }
   ]
  },
  {
   "title": "QPS rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(vertx_httpserver_requests_time_seconds_count[1m])",
     "legendFormat": "Total QPS[{{job}}]"
    },
    {
     "expr": "irate(vertx_httpserver_requests{path=~\"$path\", state=~\"total\"}[1m])",
     "legendFormat": "QPS[{{job}}, {{path}}]"
    }
   ]
  },
  {
   "title": "Processing time request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, avg(rate(vertx_httpserver_requests_time_seconds_bucket{job=~\"$job\"}[1m])) by (le))",
     "legendFormat": "Processing time [ quantile=0.95 ]"
    }
   ]
  },
  {
   "title": "Response Code Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_httpserver_responses{instance=~\"$instance\", job=~\"$job\", code=~\"$response_code\"}) / sum(vertx_httpserver_responses{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "response_code_ratio"
    }
   ]
  }
 ]
}